name: Build OSD main on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  #  build-opensearch-dashboards:
  #    uses: ./.github/workflows/build-opensearch-dashboards.yml
  #    with:
  #      deployment_name: "deployments/main"
  #      version: "3.0.0"
  #      node_version: "20.18.3"
  #    secrets:
  #      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build-future-playground:
    uses: ./.github/workflows/build-opensearch-dashboards.yml
    with:
      deployment_name: "playgrounds/future-playground"
      version: "3.2.0"
      node_version: "20.18.3"
      essential_plugins: "securityDashboards,assistantDashboards,flowFrameworkDashboards,anomalyDetectionDashboards,mlCommonsDashboards"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build-notebook:
    uses: ./.github/workflows/build-opensearch-dashboards.yml
    with:
      deployment_name: "playgrounds/notebook-enhancement-playground"
      version: "3.1.0"
      node_version: "20.18.3"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
